# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/EncryptionSubsystemPinConstraints_KC705.xdc

# Block Designs: bd/EncryptionSubsystem/EncryptionSubsystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem || ORIG_REF_NAME==EncryptionSubsystem}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_EncryptionEngine_0_0/EncryptionSubsystem_EncryptionEngine_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_EncryptionEngine_0_0 || ORIG_REF_NAME==EncryptionSubsystem_EncryptionEngine_0_0}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_microblaze_0_0/EncryptionSubsystem_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_microblaze_0_0 || ORIG_REF_NAME==EncryptionSubsystem_microblaze_0_0}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_dlmb_v10_0/EncryptionSubsystem_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_dlmb_v10_0 || ORIG_REF_NAME==EncryptionSubsystem_dlmb_v10_0}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_ilmb_v10_0/EncryptionSubsystem_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_ilmb_v10_0 || ORIG_REF_NAME==EncryptionSubsystem_ilmb_v10_0}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_dlmb_bram_if_cntlr_0/EncryptionSubsystem_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==EncryptionSubsystem_dlmb_bram_if_cntlr_0}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_ilmb_bram_if_cntlr_0/EncryptionSubsystem_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==EncryptionSubsystem_ilmb_bram_if_cntlr_0}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_lmb_bram_0/EncryptionSubsystem_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_lmb_bram_0 || ORIG_REF_NAME==EncryptionSubsystem_lmb_bram_0}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_clk_wiz_1_0/EncryptionSubsystem_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_clk_wiz_1_0 || ORIG_REF_NAME==EncryptionSubsystem_clk_wiz_1_0}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_rst_clk_wiz_1_100M_0/EncryptionSubsystem_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==EncryptionSubsystem_rst_clk_wiz_1_100M_0}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_microblaze_0_axi_periph_0/EncryptionSubsystem_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_microblaze_0_axi_periph_0 || ORIG_REF_NAME==EncryptionSubsystem_microblaze_0_axi_periph_0}]

# IP: bd/EncryptionSubsystem/ip/EncryptionSubsystem_xbar_1/EncryptionSubsystem_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_xbar_1 || ORIG_REF_NAME==EncryptionSubsystem_xbar_1}]

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_microblaze_0_0/EncryptionSubsystem_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_microblaze_0_0 || ORIG_REF_NAME==EncryptionSubsystem_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_microblaze_0_0/EncryptionSubsystem_microblaze_0_0_ooc_debug.xdc

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_microblaze_0_0/EncryptionSubsystem_microblaze_0_0_ooc.xdc

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_dlmb_v10_0/EncryptionSubsystem_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_dlmb_v10_0 || ORIG_REF_NAME==EncryptionSubsystem_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_dlmb_v10_0/EncryptionSubsystem_dlmb_v10_0_ooc.xdc

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_ilmb_v10_0/EncryptionSubsystem_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_ilmb_v10_0 || ORIG_REF_NAME==EncryptionSubsystem_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_ilmb_v10_0/EncryptionSubsystem_ilmb_v10_0_ooc.xdc

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_dlmb_bram_if_cntlr_0/EncryptionSubsystem_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_ilmb_bram_if_cntlr_0/EncryptionSubsystem_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_lmb_bram_0/EncryptionSubsystem_lmb_bram_0_ooc.xdc

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_clk_wiz_1_0/EncryptionSubsystem_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_clk_wiz_1_0 || ORIG_REF_NAME==EncryptionSubsystem_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_clk_wiz_1_0/EncryptionSubsystem_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_clk_wiz_1_0 || ORIG_REF_NAME==EncryptionSubsystem_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_clk_wiz_1_0/EncryptionSubsystem_clk_wiz_1_0_ooc.xdc

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_rst_clk_wiz_1_100M_0/EncryptionSubsystem_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==EncryptionSubsystem_rst_clk_wiz_1_100M_0}]

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_rst_clk_wiz_1_100M_0/EncryptionSubsystem_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EncryptionSubsystem_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==EncryptionSubsystem_rst_clk_wiz_1_100M_0}]

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_rst_clk_wiz_1_100M_0/EncryptionSubsystem_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/EncryptionSubsystem/ip/EncryptionSubsystem_xbar_1/EncryptionSubsystem_xbar_1_ooc.xdc

# XDC: bd/EncryptionSubsystem/EncryptionSubsystem_ooc.xdc
