# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/tjlw/HWAcceleratedEncryptionEngine/HWAcceleratedEncryptionEngine.tmp/EncryptionEngine_Sandbox_v1_0_v1_0_project/EncryptionEngine_Sandbox_v1_0_v1_0_project.cache/wt [current_project]
set_property parent.project_path /home/tjlw/HWAcceleratedEncryptionEngine/HWAcceleratedEncryptionEngine.tmp/EncryptionEngine_Sandbox_v1_0_v1_0_project/EncryptionEngine_Sandbox_v1_0_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.2 [current_project]
set_property ip_repo_paths /home/tjlw/ip_repo [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog {
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/inc_RS232_TFree.h
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/inc_RS232_T100.h
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/inc_RS232_T500.h
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/inc_RS232_T300.h
}
set_property file_type "Verilog Header" [get_files /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/inc_RS232_TFree.h]
set_property file_type "Verilog Header" [get_files /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/inc_RS232_T100.h]
set_property file_type "Verilog Header" [get_files /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/inc_RS232_T500.h]
set_property file_type "Verilog Header" [get_files /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/inc_RS232_T300.h]
read_verilog -library xil_defaultlib {
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/table_aes_128_T500.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/table_aes_128_TFree.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/round_aes_128_T500.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/u_xmit_RS232_TFree.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/u_xmit_RS232_T100.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/u_rec_RS232_T500.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/TSC_aes_128_T500.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/u_rec_RS232_T300.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/u_xmit_RS232_T300.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/round_aes_128_TFree.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/u_rec_RS232_T100.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/u_xmit_RS232_T500.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/aes_128_T500.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/u_rec_RS232_TFree.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/uart_RS232_T300.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/uart_RS232_T100.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/aes_128_TFree.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/uart_RS232_T500.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/uart_RS232_TFree.v
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/top_aes_128_T500.v
}
read_vhdl -library xil_defaultlib {
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/modmult_rsacypher_T300.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/modmult_rsacypher_TFree.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/modmult_rsacypher_T100.vhd
  /home/tjlw/HWAcceleratedEncryptionEngine/HWAcceleratedEncryptionEngine.tmp/EncryptionEngine_Sandbox_v1_0_v1_0_project/EncryptionEngine_Sandbox_v1_0_v1_0_project.srcs/sources_1/new/Counter.vhd
  /home/tjlw/HWAcceleratedEncryptionEngine/HWAcceleratedEncryptionEngine.tmp/EncryptionEngine_Sandbox_v1_0_v1_0_project/EncryptionEngine_Sandbox_v1_0_v1_0_project.srcs/sources_1/new/Checker.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/rsacypher_TFree.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/rsacypher_T300.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/rsacypher_T100.vhd
  /home/tjlw/HWAcceleratedEncryptionEngine/HWAcceleratedEncryptionEngine.tmp/EncryptionEngine_Sandbox_v1_0_v1_0_project/EncryptionEngine_Sandbox_v1_0_v1_0_project.srcs/sources_1/new/SandboxController.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/EncryptionEngine_v1_0_RSA_AXI.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/EncryptionEngine_v1_0_RS232_AXI.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/EncryptionEngine_v1_0_Control_AXI.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/EncryptionEngine_v1_0_AES_AXI.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/EncryptionEngine.vhd
  /home/tjlw/ip_repo/EncryptionEngine_Sandbox_1.0/src/EncryptionEngine_Sandbox_v1_0.vhd
}
synth_design -top EncryptionEngine_Sandbox_v1_0 -part xc7k325tffg900-2
write_checkpoint -noxdef EncryptionEngine_Sandbox_v1_0.dcp
catch { report_utilization -file EncryptionEngine_Sandbox_v1_0_utilization_synth.rpt -pb EncryptionEngine_Sandbox_v1_0_utilization_synth.pb }
